name: ms_news
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  logger: ^1.4.0
  intl: ^0.18.1
  dartz: ^0.10.1
  path_provider: ^2.0.15
  equatable: ^2.0.5
  flutter_displaymode: ^0.6.0
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flex_color_scheme: ^7.1.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  auto_route: ^7.7.0
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  auto_route_generator: ^7.2.0

scripts: derry.yaml

# import_sorter config
# TODO: filter regexp need to correct
import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/\w+\.\w+\.dart

flutter:
  uses-material-design: true

  assets:
    - assets/env/.env
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
